# Generated by Django 5.0.1 on 2024-09-17 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delivery_remove_buy_delivery_not_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
