# Generated by Django 5.1.1 on 2024-09-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_shopreg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopreg',
            name='password',
            field=models.TextField(),
        ),
    ]
