# Generated by Django 5.0.1 on 2024-10-02 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
