# Generated by Django 5.0.1 on 2024-11-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='del_boy',
        ),
        migrations.AlterField(
            model_name='buy',
            name='date_of_buying',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
