# Generated by Django 5.0.1 on 2024-11-03 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_buy_del_boy_alter_buy_date_of_buying_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='payment_status',
            new_name='delivery_status',
        ),
    ]
