# Generated by Django 5.0.1 on 2024-11-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_payment_status_buy_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='date_of_buying',
            field=models.TextField(),
        ),
    ]
